title: "Jonathan Brinkerhoff"
email: "j.brinkerhoff@live.com"
description: "Portfolio of Jonathan Brinkerhoff â€“ data analyst, aspiring data scientist, and developer"
baseurl: /REPOSITORY-NAME/
domain: bhoff909.github.io
url: https://bhoff909.github.io
theme: leap-day
markdown: kramdown
plugins:
  - jekyll-feed
