title: "Jonathan Brinkerhoff"
email: "j.brinkerhoff@live.com"
description: "Portfolio of Jonathan Brinkerhoff â€“ data analyst, aspiring data scientist, and developer"
baseurl: "" # leave empty for root domain
url: "https://bhoff909.github.io"
theme: leap-day
markdown: kramdown
plugins:
  - jekyll-feed
