title: Brian Hoffman
description: Your personal description goes here
baseurl: "" # leave empty for username.github.io
url: "https://bhoff909.github.io" # change to your domain if using one

# Theme settings
theme: jekyll-theme-leap-day
github:
  is_project_page: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
email: your.email@example.com
twitter_username: yourtwitter
github_username: bhoff909
linkedin_username: yourlinkedin

# Navigation links
navbar-links:
  About: "about"
  Projects: "projects"
  Blog: "blog"
  Contact: "contact"
